from plotter import Structure, Point, PointLoad, Beam, Moment, Length, DistributedLoad, Support, RotationSpring
from plotter import plot

A = Point(0,0, 'A', labelpos=('top', 'left'))
B = Point(5,A.y, 'B', labelpos=('top', 'right'))
D = Point(A.x,5, 'D', labelpos=('bottom', 'right'))
C = Point(2,D.y, 'C', labelpos=('bottom', 'left'))
E = Point(-1.5,D.y, 'E', labelpos=('top', 'right'))
M1 = Moment(D, -20, clock_wise=True)
F1 = PointLoad(C, 10, dxdy=(0,2), labelpos=('top', 'right'))
L1 = Length(A, D, 'y', ypos='left')
L2 = Length(E, C, 'x')
AD = Beam(A, D)
AD.add_hinge(is_begin=False)
EC = Beam(E, C)
CB = Beam(B, C, 'EI = 2000\nA=300', labelpos=('bottom','left'), anglelabel=True)
q1 = DistributedLoad(C, B, 10, 20, angle=CB.angle-90, n_arrow=10)
print(CB.angle)
As = Support(A, 'pinned')
Bs = Support(B, 'pinned')
Es = Support(E, 'fixed', angle=30+180)
RS = RotationSpring(A)
s = Structure()
s.add_beam(AD)
s.add_beam(EC)
s.add_beam(CB)
s.add_hinge(C)
s.add_support(As)
s.add_support(Bs)
s.add_support(Es)
s.add_moment(M1)
s.add_pointload(F1)
s.add_distributedload(q1)
s.add_rotationspring(RS)
s.add_length(L1)
s.add_length(L2)
#plot(s)



