from plotter import Structure, Point, LatexLabel, PointLoad, Beam, TwistingMoment, ParabolicBeam, DeformedBeam, Moment, Length, DistributedLoad, Support, RotationSpring, TranslationSpring
from plotter import plot
from plotter import Mgraph, Vgraph, Ngraph
import sympy

A = Point(0,0, 'A', labelpos=('top', 'left'))
B = Point(10,A.y, 'B', labelpos=('top', 'right'))
D = Point(A.x,5, 'D', labelpos=('bottom', 'right'))
C = Point(2,D.y, 'C', labelpos=('bottom', 'left'))
E = Point(-1.5,D.y, 'E', labelpos=('top', 'right'))
F = LatexLabel(5, 5, r'$\phi_a$, $w_b$, $\delta_c$')
M1 = Moment(D, -20, clock_wise=True)
F1 = PointLoad(C, 10, dxdy=(0,2), labelpos=('top', 'right'))
TM1 = TwistingMoment(A, 10, dxdy=(0,2))
L1 = Length(A, D, 'y', ypos='left')
L2 = Length(E, C, 'x')
x = sympy.symbols('x')
AD = Beam(A, C)
AD.add_hinge('end')
print(AD.hinges)
EC = Beam(E, C)
CB = Beam(B, C, 'EI = 2000\nA=300', labelpos=('bottom','left'), anglelabel=False)
q1 = DistributedLoad(C, B, -10, angle=CB.angle, n_arrow=5, is_twistedmoment=True, flip=True)
As = Support(A, 'pinned')
Bs = Support(B, 'pinned')
Es = Support(E, 'fixed', angle=30+180)
#RS = RotationSpring(A)
s = Structure()
s.add_label(F)
s.add_beam(AD)
s.add_beam(EC)
s.add_beam(CB)
s.add_hinge(C)
s.add_support(As)
s.add_support(Bs)
s.add_support(Es)
s.add_moment(M1)
s.add_pointload(F1)
s.add_twistingmoment(TM1)
s.add_distributedload(q1)
#s.add_rotationspring(RS)
s.add_length(L1)
s.add_length(L2)
#s.opaque_list(AD, EC, CB, M1, F1, q1, L1, L2, As, Bs, Es)
#s.dashed_list(AD)
plot(s)

# A = Point(0,0, 'A', labelpos=('top', 'left'))
# B = Point(A.x+1.5,8, 'B', labelpos=('top', 'right'))
# C = Point(-1, 0)
# D = Point(0,4)
# E = Point(-1, 4)
# Cs = Support(C, 'pinned', angle=90)
# Bs = Support(B, 'pinned', angle=90)
# AB = Beam(A, B, anglelabel=True)
# CA = TranslationSpring(C, A)
# L = Length(A, B, ax='y', ypos='right')
# F = DistributedLoad(A, B, 40, 40, angle=AB.angle-90)
# st = Structure()
# st.add_beam(AB)
# st.add_support(Cs)
# st.add_support(Bs)
# st.add_length(L)
# st.add_distributedload(F)
# st.add_translationspring(CA)
# #plot(st)

# A = Point(0,0, 'A', labelpos=('top', 'right'))
# B = Point(3, A.y, 'B')
# C = Point(2.1, A.y, 'Ç')
# D = Point(1, 0)
# E = Point(1.5, 0)
# G = Point(1.5, -1)
# AB = Beam(A, B)
# EG = Beam(E, G)
# As = Support(A, 'fixed', AB.angle-90)
# Bs = Support(B, 'roller')
# EG.add_hinge('start')
# L1 = Length(A, C, ax='x')
# L2 = Length(C, B, ax='x')
# F = PointLoad(C, 50, 'kN', (7, 24), anglelabel=True)
# M = Moment(B, 20, angle=20)
# q = DistributedLoad(E, G, 5, 15, angle=180, labelpos_end=('bottom', 'center'))
# R = RotationSpring(B, 10)
# s1 = Structure()
# s1.add_beam(AB)
# s1.add_beam(EG)
# s1.add_support(As)
# s1.add_support(Bs)
# s1.add_length(L1)
# s1.add_length(L2)
# s1.add_hinge(D)
# s1.add_pointload(F)
# s1.add_moment(M)
# s1.add_distributedload(q)
# s1.add_rotationspring(R)
# #plot(s1)

# A = Point(0, 6, 'A', ('top', 'right'))
# B = Point(4.5, 0, 'B', ('top', 'right'))
# C = Point(10, 0, 'C', ('top', 'center'))
# D = Point(10, 6, 'D', ('bottom','center'))
# E = Point(20, 6, 'E', ('bottom','center'))
# S = Point(16, 6, 'S', ('bottom','right'))
# AE = Beam(A, E)
# AB = Beam(A, B, anglelabel=True)
# CS = Beam(C, S, anglelabel=True)
# As = Support(A, 'roller', angle=90)
# Bs = Support(B, 'pinned')
# Cs = Support(C, 'fixed', angle=CS.angle-90)
# CS.add_hinge('end')
# q = DistributedLoad(D, E, 18)
# M = Moment(A, 10, angle=20)
# F = PointLoad(Point(8,6), 10, dxdy=(-2, 4), anglelabel=True)
# Ly = Length(E, Point(20,0), 'y', ypos='right')
# Lx1 = Length(Point(0,0), B)
# Lx2 = Length(B,C)
# Lx3 = Length(C, Point(16,0))
# Lx4 = Length(Point(16,0), Point(20,0))
# s2 = Structure()
# s2.add_beam(AE, AB, CS)
# s2.add_support(As, Bs, Cs)
# s2.add_distributedload(q)
# s2.add_moment(M)
# s2.add_pointload(F)
# s2.add_length(Ly, Lx1, Lx2, Lx3, Lx4)
# #plot(s2)

# for Dy in [2,3,4]:
#     A = Point(0,0, 'A', ('center', 'left'))
#     B = Point(4,0, 'B', ('center', 'right'))
#     C = Point(2,0, 'C', ('bottom', 'center'))
#     D = Point(2, Dy, 'D', ('bottom', 'right'))
#     AB = Beam(A, B)
#     CD = Beam(C, D)
#     As = Support(A, 'roller')
#     Bs = Support(B, 'pinned')
#     Ds = Support(D, 'fixed', angle=180)
#     q = DistributedLoad(A, B, 2, 13)
#     M = Moment(C, 10, angle=20+180, labelpos=('bottom', 'center'))
#     F = PointLoad(B, 10, dxdy=(2, 4), anglelabel=False)
#     Ly = Length(C, D, 'y', ypos='right')
#     Lx1 = Length(A, C)
#     Lx2 = Length(C, B)
#     s3 = Structure()
#     s3.add_beam(AB, CD)
#     s3.add_support(As, Bs, Ds)
#     s3.add_distributedload(q)
#     s3.add_moment(M)
#     s3.add_pointload(F)
#     s3.add_length(Ly, Lx1, Lx2)
#     #plot(s3, name=f'{Dy}', format='png', is_seed=False)

# A = Point(0,0, 'A', labelpos=('top', 'left'))
# B = Point(A.x+1.5,8, 'B', labelpos=('top', 'right'))
# C = Point(4, 8, 'C')
# AB = Beam(A, B, anglelabel=True)
# BC = Beam(B, C)

# M = Ngraph()
# M.add_beam(AB, (0,0), (0,2), (1,2), (2,3), (4,0), M.parabole(4, 4, 6, -1, 8, 4), (8,0))
# M.add_beam(BC, (0,0), (1, 3), M.parabole(1, 3, 1.5, -5, 2, 5), (2,0))
# #M.plot()



# X = Point(0,0)
# Y = Point(12, 0)
# XY = Beam(X, Y)

# V = Vgraph()
# V.add_beam(XY, (0,0), (2, 16), (2, -32), (8, 16), (10, 16), (10, 0), (12,0))
# #V.flip_sign(XY)
# #V.plot()

# N = Ngraph()
# N.add_beam(XY, (0,0), (2, 16), (2, -32), (8, 16), (10, 16), (10, 0), (12,0))
# #N.flip_sign(XY)
# #N.plot()

